main: com.twanl.realtimesupport.RealTimeSupport
name: RealTimeSupport
version: 1.7.2
author: Twan L
api-version: "1.13"


commands:
  realtimesupport:
    usage: /<command>
    description: main command
    aliases: [rs]